/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RebrandingRouteImport } from './routes/rebranding'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as CicloDeMarcaRouteImport } from './routes/ciclo-de-marca'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as AdminProjetosRouteImport } from './routes/admin/projetos'
import { Route as AdminDiagnosticoRouteImport } from './routes/admin/diagnostico'
import { Route as AdminContatosRouteImport } from './routes/admin/contatos'
import { Route as ApiPublicDiagnosticLeadRouteImport } from './routes/api/public/diagnostic-lead'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AdminCasesIdRouteImport } from './routes/admin/cases.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RebrandingRoute = RebrandingRouteImport.update({
  id: '/rebranding',
  path: '/rebranding',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const CicloDeMarcaRoute = CicloDeMarcaRouteImport.update({
  id: '/ciclo-de-marca',
  path: '/ciclo-de-marca',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContatosRoute = AdminContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicDiagnosticLeadRoute = ApiPublicDiagnosticLeadRouteImport.update({
  id: '/api/public/diagnostic-lead',
  path: '/api/public/diagnostic-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesIdRoute = AdminCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/branding': typeof BrandingRoute
  '/ciclo-de-marca': typeof CicloDeMarcaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/rebranding': typeof RebrandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostic-lead': typeof ApiPublicDiagnosticLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/ciclo-de-marca': typeof CicloDeMarcaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/rebranding': typeof RebrandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostic-lead': typeof ApiPublicDiagnosticLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/branding': typeof BrandingRoute
  '/ciclo-de-marca': typeof CicloDeMarcaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/rebranding': typeof RebrandingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostic-lead': typeof ApiPublicDiagnosticLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/branding'
    | '/ciclo-de-marca'
    | '/diagnostico'
    | '/diario'
    | '/estudio'
    | '/rebranding'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/diagnostico'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/admin/'
    | '/admin/cases/$id'
    | '/api/public/contact'
    | '/api/public/diagnostic-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branding'
    | '/ciclo-de-marca'
    | '/diagnostico'
    | '/diario'
    | '/estudio'
    | '/rebranding'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/diagnostico'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/admin'
    | '/admin/cases/$id'
    | '/api/public/contact'
    | '/api/public/diagnostic-lead'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/branding'
    | '/ciclo-de-marca'
    | '/diagnostico'
    | '/diario'
    | '/estudio'
    | '/rebranding'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/diagnostico'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/admin/'
    | '/admin/cases/$id'
    | '/api/public/contact'
    | '/api/public/diagnostic-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BrandingRoute: typeof BrandingRoute
  CicloDeMarcaRoute: typeof CicloDeMarcaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiarioRoute: typeof DiarioRoute
  EstudioRoute: typeof EstudioRoute
  RebrandingRoute: typeof RebrandingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  CasesSlugRoute: typeof CasesSlugRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDiagnosticLeadRoute: typeof ApiPublicDiagnosticLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rebranding': {
      id: '/rebranding'
      path: '/rebranding'
      fullPath: '/rebranding'
      preLoaderRoute: typeof RebrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciclo-de-marca': {
      id: '/ciclo-de-marca'
      path: '/ciclo-de-marca'
      fullPath: '/ciclo-de-marca'
      preLoaderRoute: typeof CicloDeMarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/diagnostico': {
      id: '/admin/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contatos': {
      id: '/admin/contatos'
      path: '/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminContatosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/diagnostic-lead': {
      id: '/api/public/diagnostic-lead'
      path: '/api/public/diagnostic-lead'
      fullPath: '/api/public/diagnostic-lead'
      preLoaderRoute: typeof ApiPublicDiagnosticLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/$id': {
      id: '/admin/cases/$id'
      path: '/cases/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AdminCasesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContatosRoute: typeof AdminContatosRoute
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesIdRoute: typeof AdminCasesIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContatosRoute: AdminContatosRoute,
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesIdRoute: AdminCasesIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BrandingRoute: BrandingRoute,
  CicloDeMarcaRoute: CicloDeMarcaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiarioRoute: DiarioRoute,
  EstudioRoute: EstudioRoute,
  RebrandingRoute: RebrandingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  CasesSlugRoute: CasesSlugRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDiagnosticLeadRoute: ApiPublicDiagnosticLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
