/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  EstudioRoute: typeof EstudioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  EstudioRoute: EstudioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
