/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicosRebrandingRouteImport } from './routes/servicos.rebranding'
import { Route as ServicosBrandingRouteImport } from './routes/servicos.branding'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as AdminProjetosRouteImport } from './routes/admin/projetos'
import { Route as AdminContatosRouteImport } from './routes/admin/contatos'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AdminCasesIdRouteImport } from './routes/admin/cases.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServicosRebrandingRoute = ServicosRebrandingRouteImport.update({
  id: '/servicos/rebranding',
  path: '/servicos/rebranding',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosBrandingRoute = ServicosBrandingRouteImport.update({
  id: '/servicos/branding',
  path: '/servicos/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContatosRoute = AdminContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesIdRoute = AdminCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/servicos/branding': typeof ServicosBrandingRoute
  '/servicos/rebranding': typeof ServicosRebrandingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/servicos/branding': typeof ServicosBrandingRoute
  '/servicos/rebranding': typeof ServicosRebrandingRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/diario': typeof DiarioRoute
  '/estudio': typeof EstudioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/contatos': typeof AdminContatosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/servicos/branding': typeof ServicosBrandingRoute
  '/servicos/rebranding': typeof ServicosRebrandingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/servicos/branding'
    | '/servicos/rebranding'
    | '/admin/'
    | '/admin/cases/$id'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/servicos/branding'
    | '/servicos/rebranding'
    | '/admin'
    | '/admin/cases/$id'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/diario'
    | '/estudio'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/contatos'
    | '/admin/projetos'
    | '/cases/$slug'
    | '/servicos/branding'
    | '/servicos/rebranding'
    | '/admin/'
    | '/admin/cases/$id'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DiarioRoute: typeof DiarioRoute
  EstudioRoute: typeof EstudioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  CasesSlugRoute: typeof CasesSlugRoute
  ServicosBrandingRoute: typeof ServicosBrandingRoute
  ServicosRebrandingRoute: typeof ServicosRebrandingRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/servicos/rebranding': {
      id: '/servicos/rebranding'
      path: '/servicos/rebranding'
      fullPath: '/servicos/rebranding'
      preLoaderRoute: typeof ServicosRebrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/branding': {
      id: '/servicos/branding'
      path: '/servicos/branding'
      fullPath: '/servicos/branding'
      preLoaderRoute: typeof ServicosBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contatos': {
      id: '/admin/contatos'
      path: '/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminContatosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/$id': {
      id: '/admin/cases/$id'
      path: '/cases/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AdminCasesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContatosRoute: typeof AdminContatosRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesIdRoute: typeof AdminCasesIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContatosRoute: AdminContatosRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesIdRoute: AdminCasesIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DiarioRoute: DiarioRoute,
  EstudioRoute: EstudioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  CasesSlugRoute: CasesSlugRoute,
  ServicosBrandingRoute: ServicosBrandingRoute,
  ServicosRebrandingRoute: ServicosRebrandingRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
